### PR TITLE
[#176314485] Use x-client-ip for internal calls

### PR DESCRIPTION
**Pull request by gunzip**
This is a fix since req.connection.remoteAddress returns the internal docker host IP

### CODE REVIEW

**Comment by balanza** [comment]
I don't like the fallback mechanism, as this enables both scenarios (behind proxy and not) while those are actually mutually exclusives.
I'd rather use an application-wide config stating if we expect incoming traffic to come from a proxy or not; then we can implement a logic like
```
IF is behind proxy
   IP = req.ip
ELSE
  IP = req.headers["x-client-ip"]
```

What do you think?

**Comment by gunzip** [comment]
Since the condition `IF is behind proxy` equals `req.headers["x-forwarded-for"]` I don't find a real added value in splitting the condition. The logic with this PR is indeed:

IF is behind proxy
  IP = req.headers["x-forwarded-for"] (= req.ip)
ELSE
  IP = req.headers["x-client-ip"]

**Comment by balanza** [comment]
> Since the condition `IF is behind proxy` equals `req.headers["x-forwarded-for"]` I don't find a real added value in splitting the condition. The logic with this PR is indeed:
> 
> ```
> IF is behind proxy
>   IP = req.headers["x-forwarded-for"] (= req.ip)
> ELSE
>   IP = req.headers["x-client-ip"]
> ```

It's actually
```
IF req has header "x-forwarded-for"
  IP = req.headers["x-forwarded-for"]
ELSE
  IP = req.headers["x-client-ip"]
```

Anyway, it's still a weak check that could be easily forged I think. I'm fine with the actual implementation.

**Review by balanza — APPROVED** [review]

**Comment by gunzip** [comment]
> Anyway, it's still a weak check that could be easily forged I think.

The real threat would be forging a custom value for `x-forwarded-for`. This is avoided at the application gateway level with a custom rule that overwrites that value with the one of the remote address. Every call from the user (IO App) pass though the application gateway so the value cannot be forged for external calls.

About internal calls (made from the functions towards the internal backend, the one that isn't added to the application gateway pool so it's unreachable from the outside), they don't set x-forwarded-for so we must fallback on x-client-ip which can be forged only if the function-app is compromised and, in this scenario, you don't need to forge it at all.

**Pull request merged**
