### PR TITLE
[#IP-122] Reduce log data ingestion

### PR DESCRIPTION
**Pull request by pasqualedevita**
#### List of Changes

1. increase log sampling from 20 to 5 (lowest value reduce log ingestion in application insights)

#### Motivation and Context

Cost savings reducing log data ingestion in application insights

#### How Has This Been Tested?

Same change applied on fn3app1 https://github.com/pagopa/io-functions-app/pull/156

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pasqualedevita** [comment]
@balanza @BurnedMarshal @AleDore is ok for u?

**Comment by pasqualedevita** [comment]
@balanza @BurnedMarshal can we merge?

**Review by AleDore — APPROVED** [review]
LGTM. Let's keep in mind that by reducing sampling percentage we can lose some specific errors, but if this risk I reasonable we can merge :)

**Comment by pasqualedevita** [comment]
> LGTM. Let's keep in mind that by reducing sampling percentage we can lose some specific errors, but if this risk is reasonable we can merge :)

risk is reasonable, anyway we add same configuration on all others functions

**Comment by BurnedMarshal** [comment]
@pasqualedevita The sampling percentage should be configurable for `io-backend` with `APPINSIGHTS_SAMPLING_PERCENTAGE` ENV variable https://github.com/pagopa/io-backend/blob/f763728819ee557ae88bfced6aad3513c83f22ab/src/server.ts#L79

**Pull request merged**
