### PR TITLE
[#174749917] Create bpdToken and update getSession

### PR DESCRIPTION
**Pull request by BurnedMarshal**

### CODE REVIEW

**Review by gunzip — APPROVED** [review]
why draft?

**Comment by BurnedMarshal** [comment]
> why draft?

I'm finishing local testing with `io-mock`

**Comment by gunzip** [comment]
do you manage to test the upgrade of a user session? (if session token and expire time are kept)

**Comment by BurnedMarshal** [comment]
> do you manage to test the upgrade of a user session? (if session token and expire time are kept)

yes, I'm testing the creation of the token and double-check the TTL of all the keys involved.

**Pull request merged**
