### PR TITLE
[#166090151] Added spid validator as IDP

### PR DESCRIPTION
**Pull request by Edigio**
Added spid validator as IDP

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * ⚙️ [#166090151](https://www.pivotaltracker.com/story/show/166090151): Validare l'implementazione SPID con lo SPID validator

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Edigio** [comment]
Run Backend and Spid Validator locally:

validator

**Comment by Edigio** [comment]
Checks Service Provider report:
1_report_validator
2_report_validator
3_report_simulatore

**Comment by Edigio** [comment]
It's possible send more response from the Spid validator to Service provider (backend-app), there are two examples:

**Correct response:**
validator_ok

**Not correct response**
validator_error

**Pull request closed without merging**
